name: Build LuaDec

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build the project
      - name: Build LuaDec
        run: |
          make

      # Optional: Test the build
      - name: Run Tests
        run: |
          make test

      # Optional: Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: luadec-binaries
          path: ./luadec
