name: LuaDec

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build the project
      - name: Build LuaDec
        run: |
          cd src  # Replace 'src' with the directory containing the Makefile
          make

      # Optional: Run Tests
      - name: Run Tests
        run: |
          cd src  # Replace 'src' with the directory containing the tests
          make test

      # Optional: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: luadec-binaries
          path: ./src/luadec  # Adjust this path to point to your built binaries
