name: Build LuaDec

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # List all files to debug repository structure
      - name: List Repository Files
        run: ls -R

      # Set up dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build the project
      - name: Build LuaDec
        run: |
          # Locate the directory containing the Makefile
          if [ -f Makefile ]; then
            echo "Found Makefile in the root directory."
            make
          else
            echo "Makefile not found in the root directory."
            for dir in $(find . -type f -name Makefile -exec dirname {} \;); do
              echo "Found Makefile in $dir."
              cd "$dir"
              make
              break
            done
          fi

      # Optional: Run Tests
      - name: Run Tests
        run: |
          if [ -d tests ]; then
            echo "Running tests..."
            make test
          else
            echo "No tests directory found, skipping."
          fi

      # Optional: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: luadec-binaries
          path: |
            ./luadec  # Adjust this path to point to your built binaries, if applicable
            ./build   # Add any other paths as needed
